order: 29
id: outlook-other-item-apis-item-id-compose
name: Get an item ID in compose mode
description: Gets an item ID in compose mode.
host: OUTLOOK
api_set:
    Mailbox: '1.8'
script:
    content: |
        $("#run").on("click", run);
          
        function run() {
            Office.context.mailbox.item.getItemIdAsync((result) => {
                if (result.status === Office.AsyncResultStatus.Failed) {
                    console.error(`getItemIdAsync failed with message: ${result.error.message}`);
                    return;
                }

                console.log(result.value);
            });
        }
    language: typescript
template:
    content: |
        <section class="ms-Fabric ms-font-m">
          <p>This sample shows how to get an item ID in compose mode.</p>
          <p><b>Required mode</b>: Compose</p>
        </section>

        <section class="ms-Fabric samples ms-font-m">
          <h3>Try it out</h3>
          <p>Before you can get the item ID, you must first save the mail item.</p>
          <button id="run" class="ms-Button">
            <div class="ms-Button-label">Get item ID</div>
          </button>
        </section>
    language: html
style:
    content: |
        section.samples {
            margin-top: 20px;
        }

        section.samples .ms-Button, section.setup .ms-Button {
            display: block;
            margin-bottom: 5px;
            margin-left: 20px;
            min-width: 80px;
        }
    language: css
libraries: |
    https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js
    @types/office-js

    office-ui-fabric-core@11.1.0/dist/css/fabric.min.css
    office-ui-fabric-js@1.5.0/dist/css/fabric.components.min.css

    core-js@2.4.1/client/core.min.js
    @types/core-js

    jquery@3.1.1
    @types/jquery@3.3.1