order: 29
id: outlook-other-item-apis-item-id-compose
name: Get an item ID in compose mode
description: Gets an item ID in compose mode.
host: OUTLOOK
api_set:
    Mailbox: '1.8'
script:
    content: |-
        document.getElementById("run").addEventListener("click", run);
          
        function run() {
            Office.context.mailbox.item.getItemIdAsync((result) => {
                if (result.status === Office.AsyncResultStatus.Failed) {
                    console.error(`getItemIdAsync failed with message: ${result.error.message}`);
                    return;
                }

                console.log(result.value);
            });
        }
    language: typescript
template:
    content: |-
        <section class = "description">
          <p>This sample shows how to get an item ID in compose mode.</p>
          <p><b>Required mode</b>: Compose</p>
        </section>
        <section class = "samples">
          <h3>Try it out</h3>
          <p>Before you can get the item ID, you must first save the mail item.</p>
          <button id = "run" >
            <div>Get item ID</div>
          </button>
        </section>
    language: html
style:
    content: |-
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 14px;
            line-height: 1.5;
            padding: 10px;
        }

        section {
            margin-bottom: 20px;
        }

        h3 {
            margin-top: 0;
            margin-bottom: 10px;
            font-size: 16px;
        }

        p {
            margin: 0 0 10px 0;
        }

        button {
            background-color: #0078d4;
            color: white;
            border: none;
            padding: 8px 16px;
            font-size: 14px;
            cursor: pointer;
            border-radius: 2px;
            margin-left: 20px;
            margin-bottom: 5px;
            min-width: 80px;
            display: block;
        }

        button:hover {
            background-color: #106ebe;
        }

        button:active {
            background-color: #005a9e;
        }

        input {
            padding: 8px;
            margin: 5px 0;
            border: 1px solid #ccc;
            border-radius: 2px;
            font-size: 14px;
        }

        .header {
            text-align: center;
            background-color: #f3f2f1;
            padding: 10px;
        }
    language: css
libraries: |-
    https://appsforoffice.microsoft.com/lib/1/hosted/office.js
    https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/types/office-js/index.d.ts