order: 2
id: outlook-recipients-and-attendees-get-from-message-compose
name: Get from (Message Compose)
description: Gets who the message is from in Compose mode.
host: OUTLOOK
api_set:
    Mailbox: '1.7'
script:
    content: |-
        document.getElementById("get-from").addEventListener("click", getFrom);

        function getFrom() {
          Office.context.mailbox.item.from.getAsync(function(asyncResult) {
            if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
              const msgFrom = asyncResult.value;
              console.log("Message from: " + msgFrom.displayName + " (" + msgFrom.emailAddress + ")");
            } else {
              console.error(asyncResult.error);
            }
          });
        }
    language: typescript
template:
    content: |-
        <section>
            <p>This sample shows how to get who an email is <b>from</b>.</p>
            <p><b>Required mode</b>: Message Compose</p>
        </section>
        <section>
            <h3>Try it out</h3>
            <button id="get-from" >Who is this from?</button>
        </section>
    language: html
style:
    content: |-
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 14px;
            line-height: 1.5;
            padding: 10px;
        }

        section {
            margin-bottom: 20px;
        }

        h3 {
            margin-top: 0;
            margin-bottom: 10px;
            font-size: 16px;
        }

        p {
            margin: 0 0 10px 0;
        }

        button {
            background-color: #0078d4;
            color: white;
            border: none;
            padding: 8px 16px;
            font-size: 14px;
            cursor: pointer;
            border-radius: 2px;
            margin-left: 20px;
            margin-bottom: 5px;
            min-width: 80px;
            display: block;
        }

        button:hover {
            background-color: #106ebe;
        }

        button:active {
            background-color: #005a9e;
        }

        input {
            padding: 8px;
            margin: 5px 0;
            border: 1px solid #ccc;
            border-radius: 2px;
            font-size: 14px;
        }

        .header {
            text-align: center;
            background-color: #f3f2f1;
            padding: 10px;
        }
    language: css
libraries: |-
    https://appsforoffice.microsoft.com/lib/1/hosted/office.js
    https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/types/office-js/index.d.ts