order: 7
id: outlook-recipients-and-attendees-get-set-bcc-message-compose
name: Get and set bcc (Message Compose)
description: Gets and sets the Bcc line recipients of the message in Compose mode.
host: OUTLOOK
api_set:
    Mailbox: '1.1'
script:
    content: |
        $("#get-bcc").on("click", getBcc);
        $("#set-bcc").on("click", setBcc);

        function getBcc() {
          Office.context.mailbox.item.bcc.getAsync(function(asyncResult) {
            if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
              const msgBcc = asyncResult.value;
              console.log("Message being blind-copied to:");
              for (let i = 0; i < msgBcc.length; i++) {
                console.log(msgBcc[i].displayName + " (" + msgBcc[i].emailAddress + ")");
              }
            } else {
              console.error(asyncResult.error);
            }
          });
        }

        function setBcc() {
          const email = $("#emailBcc")
            .val()
            .toString();
          const emailArray = [email];
          Office.context.mailbox.item.bcc.setAsync(emailArray, function(asyncResult) {
            if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
              console.log("Succeeded in setting Bcc field.");
            } else {
              console.error(asyncResult.error);
            }
          });
        }
    language: typescript
template:
    content: |-
        <section class="ms-Fabric ms-font-m">
            <p class="ms-font-m">This sample shows how to get and set the <b>Bcc</b> line recipients of the email.</p>
            <p><b>Required mode</b>: Message Compose</p>
        </section>

        <section class="ms-Fabric samples ms-font-m">
            <h3>Try it out</h3>
            <div class="ms-TextField">
                <label class="ms-Label">Email address</label>
                <input id="emailBcc" class="ms-TextField-field" type="text" value="" placeholder="Who do you want to bcc?">
          </div>
                <button id="set-bcc" class="ms-Button">
            <span class="ms-Button-label">Set "Bcc"</span>
          </button>
                <button id="get-bcc" class="ms-Button">
            <span class="ms-Button-label">Get who is blind-copied</span>
          </button>
        </section>
    language: html
style:
    content: |-
        section.samples {
            margin-top: 20px;
        }

        section.samples .ms-Button, section.setup .ms-Button {
            display: block;
            margin-bottom: 5px;
            margin-left: 20px;
            min-width: 80px;
        }
    language: css
libraries: |
    https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js
    @types/office-js

    office-ui-fabric-core@11.1.0/dist/css/fabric.min.css
    office-ui-fabric-js@1.5.0/dist/css/fabric.components.min.css

    core-js@2.4.1/client/core.min.js
    @types/core-js

    jquery@3.1.1
    @types/jquery@3.3.1