order: 4
id: outlook-recipients-and-attendees-get-to-message-compose
name: Get to (Message Compose)
description: Gets the To line recipients of the message in Compose mode.
host: OUTLOOK
api_set:
    Mailbox: '1.1'
script:
    content: |
        $("#get-to").click(getTo);

        function getTo() {
          Office.context.mailbox.item.to.getAsync(function(asyncResult) {
            if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
              var msgTo = asyncResult.value;
              console.log("Message being sent to:");
              for (var i = 0; i < msgTo.length; i++) {
                console.log(msgTo[i].displayName + " (" + msgTo[i].emailAddress + ")");
              }
            } else {
              console.error(asyncResult.error);
            }
          });
        }
    language: typescript
template:
    content: |-
        <section class="ms-font-m">
            <p class="ms-font-m">This sample shows how to get the <b>To</b> line recipients of the email.</p>
            <p><b>Required mode</b>: Message Compose</p>
        </section>

        <section class="samples ms-font-m">
            <h3>Try it out</h3>
            <button id="get-to" class="ms-Button">
            <span class="ms-Button-label">Who is this to?</span>
          </button>
        </section>
    language: html
style:
    content: |-
        section.samples {
            margin-top: 20px;
        }

        section.samples .ms-Button, section.setup .ms-Button {
            display: block;
            margin-bottom: 5px;
            margin-left: 20px;
            min-width: 80px;
        }
    language: css
libraries: |
    https://appsforoffice.microsoft.com/lib/1/hosted/office.js
    @types/office-js

    office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
    office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css

    core-js@2.4.1/client/core.min.js
    @types/core-js

    jquery@3.1.1
    @types/jquery@3.3.1