order: 4
id: outlook-recipients-and-attendees-get-set-to-message-compose
name: Get and set to (Message Compose)
description: Gets and sets the To line recipients of the message in Compose mode.
host: OUTLOOK
api_set:
    Mailbox: '1.1'
script:
    content: |-
        document.getElementById("get-to").addEventListener("click", getTo);
        document.getElementById("set-to").addEventListener("click", setTo);

        function getTo() {
          Office.context.mailbox.item.to.getAsync(function(asyncResult) {
            if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
              const msgTo = asyncResult.value;
              console.log("Message being sent to:");
              for (let i = 0; i < msgTo.length; i++) {
                console.log(msgTo[i].displayName + " (" + msgTo[i].emailAddress + ")");
              }
            } else {
              console.error(asyncResult.error);
            }
          });
        }

        function setTo() {
          const email = (document.getElementById("emailTo") as HTMLInputElement).value;
          const emailArray = [email];
          Office.context.mailbox.item.to.setAsync(emailArray, function(asyncResult) {
            if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
              console.log("Succeeded in setting To field.");
            } else {
              console.error(asyncResult.error);
            }
          });
        }
    language: typescript
template:
    content: |-
        <section class="description">
            <p>This sample shows how to get and set the <b>To</b> line recipients of the email.</p>
            <p><b>Required mode</b>: Message Compose</p>
        </section>
        <section class="samples">
            <h3>Try it out</h3>
            <div class="ms-TextField">
                <label class="ms-Label">Email address</label>
                <input id="emailTo" class="ms-TextField-field" type="text" value="" placeholder="Who do you want to send this to?">
          </div>
            <button id="set-to" >Set "To"</button>
            <button id="get-to" >Get who this is to</button>
        </section>
    language: html
style:
    content: |-
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 14px;
            line-height: 1.5;
            padding: 10px;
        }

        section {
            margin-bottom: 20px;
        }

        h3 {
            margin-top: 0;
            margin-bottom: 10px;
            font-size: 16px;
        }

        p {
            margin: 0 0 10px 0;
        }

        button {
            background-color: #0078d4;
            color: white;
            border: none;
            padding: 8px 16px;
            font-size: 14px;
            cursor: pointer;
            border-radius: 2px;
            margin-left: 20px;
            margin-bottom: 5px;
            min-width: 80px;
            display: block;
        }

        button:hover {
            background-color: #106ebe;
        }

        button:active {
            background-color: #005a9e;
        }

        input {
            padding: 8px;
            margin: 5px 0;
            border: 1px solid #ccc;
            border-radius: 2px;
            font-size: 14px;
        }

        .header {
            text-align: center;
            background-color: #f3f2f1;
            padding: 10px;
        }
    language: css
libraries: |-
    https://appsforoffice.microsoft.com/lib/1/hosted/office.js
    https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/types/office-js/index.d.ts