order: 7
id: outlook-recipients-and-attendees-get-set-bcc-message-compose
name: Get and set bcc (Message Compose)
description: Gets and sets the Bcc line recipients of the message in Compose mode.
host: OUTLOOK
api_set:
    Mailbox: '1.1'
script:
    content: |-
        document.getElementById("get-bcc").addEventListener("click", getBcc);
        document.getElementById("set-bcc").addEventListener("click", setBcc);

        function getBcc() {
          Office.context.mailbox.item.bcc.getAsync(function(asyncResult) {
            if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
              const msgBcc = asyncResult.value;
              console.log("Message being blind-copied to:");
              for (let i = 0; i < msgBcc.length; i++) {
                console.log(msgBcc[i].displayName + " (" + msgBcc[i].emailAddress + ")");
              }
            } else {
              console.error(asyncResult.error);
            }
          });
        }

        function setBcc() {
          const email = (document.getElementById("emailBcc") as HTMLInputElement).value;
          const emailArray = [email];
          Office.context.mailbox.item.bcc.setAsync(emailArray, function(asyncResult) {
            if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
              console.log("Succeeded in setting Bcc field.");
            } else {
              console.error(asyncResult.error);
            }
          });
        }
    language: typescript
template:
    content: |-
        <section>
            <p>This sample shows how to get and set the <b>Bcc</b> line recipients of the email.</p>
            <p><b>Required mode</b>: Message Compose</p>
        </section>
        <section>
            <h3>Try it out</h3>
            <label>Email address</label>
            <input id="emailBcc" type="text" value="" placeholder="Who do you want to bcc?">
                <button id="set-bcc" >Set "Bcc"</button>
                <button id="get-bcc" >Get who is blind-copied</button>
        </section>
    language: html
style:
    content: |-
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            font-size: 14px;
            line-height: 1.5;
            padding: 10px;
        }

        section {
            margin-bottom: 20px;
        }

        h3 {
            margin-top: 0;
            margin-bottom: 10px;
            font-size: 16px;
        }

        p {
            margin: 0 0 10px 0;
        }

        button {
            background-color: #f0f0f0;
            color: #333333;
            border: 1px solid #8a8a8a;
            padding: 8px 16px;
            font-size: 14px;
            cursor: pointer;
            border-radius: 2px;
            margin-left: 20px;
            margin-bottom: 5px;
            min-width: 80px;
            display: block;
        }

        button:hover {
            background-color: #e0e0e0;
        }

        button:active {
            background-color: #d0d0d0;
        }

        input {
            padding: 8px;
            margin: 5px 0;
            border: 1px solid #ccc;
            border-radius: 2px;
            font-size: 14px;
        }

        .header {
            text-align: center;
            background-color: #f3f2f1;
            padding: 10px;
        }
    language: css
libraries: |-
    https://appsforoffice.microsoft.com/lib/1/hosted/office.js
    https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/master/types/office-js/index.d.ts