order: 2
id: outlook-recipients-and-attendees-get-from-message-compose
name: Get from (Message Compose)
description: Gets who the message is from in Compose mode.
host: OUTLOOK
api_set:
    Mailbox: '1.7'
script:
    content: |
        $("#get-from").click(getFrom);

        function getFrom() {
          Office.context.mailbox.item.from.getAsync(function(asyncResult) {
            if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
              var msgFrom = asyncResult.value;
              console.log("Message from: " + msgFrom.displayName + " (" + msgFrom.emailAddress + ")");
            } else {
              console.error(asyncResult.error);
            }
          });
        }
    language: typescript
template:
    content: |
        <section class="ms-font-m">
            <p class="ms-font-m">This sample shows how to get who an email is <b>from</b>.</p>
            <p><b>Required mode</b>: Message Compose</p>
        </section>

        <section class="samples ms-font-m">
            <h3>Try it out</h3>
            <button id="get-from" class="ms-Button">
            <span class="ms-Button-label">Who is this from?</span>
          </button>
        </section>
    language: html
style:
    content: |-
        section.samples {
            margin-top: 20px;
        }

        section.samples .ms-Button, section.setup .ms-Button {
            display: block;
            margin-bottom: 5px;
            margin-left: 20px;
            min-width: 80px;
        }
    language: css
libraries: |
    https://appsforoffice.microsoft.com/lib/1/hosted/office.js
    @types/office-js

    office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
    office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css

    core-js@2.4.1/client/core.min.js
    @types/core-js

    jquery@3.1.1
    @types/jquery@3.3.1
