order: 6
id: outlook-recipients-and-attendees-get-set-cc-message-compose
name: Get and set cc (Message Compose)
description: Gets and sets the Cc line recipients of the message in Compose mode.
host: OUTLOOK
api_set:
    Mailbox: '1.1'
script:
    content: |
        $("#get-cc").click(getCc);
        $("#set-cc").click(setCc);

        function getCc() {
          Office.context.mailbox.item.cc.getAsync(function(asyncResult) {
            if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
              var msgCc = asyncResult.value;
              console.log("Message being copied to:");
              for (var i = 0; i < msgCc.length; i++) {
                console.log(msgCc[i].displayName + " (" + msgCc[i].emailAddress + ")");
              }
            } else {
              console.error(asyncResult.error);
            }
          });
        }

        function setCc() {
          var email = $("#emailCc")
            .val()
            .toString();
          var emailArray = [email];
          Office.context.mailbox.item.cc.setAsync(emailArray, function(asyncResult) {
            if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
              console.log("Succeeded in setting Cc field.");
            } else {
              console.error(asyncResult.error);
            }
          });
        }
    language: typescript
template:
    content: |-
        <section class="ms-font-m">
            <p class="ms-font-m">This sample shows how to get and set the <b>Cc</b> line recipients of the email.</p>
            <p><b>Required mode</b>: Message Compose</p>
        </section>

        <section class="samples ms-font-m">
            <h3>Try it out</h3>
            <div class="ms-TextField">
                <label class="ms-Label">Email address</label>
                <input id="emailCc" class="ms-TextField-field" type="text" value="" placeholder="Who do you want cc this to?">
          </div>
                <button id="set-cc" class="ms-Button">
            <span class="ms-Button-label">Set "Cc"</span>
          </button>
                <button id="get-cc" class="ms-Button">
            <span class="ms-Button-label">Get who is copied</span>
          </button>
        </section>
    language: html
style:
    content: |-
        section.samples {
            margin-top: 20px;
        }

        section.samples .ms-Button, section.setup .ms-Button {
            display: block;
            margin-bottom: 5px;
            margin-left: 20px;
            min-width: 80px;
        }
    language: css
libraries: |
    https://appsforoffice.microsoft.com/lib/1/hosted/office.js
    @types/office-js

    office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
    office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css

    core-js@2.4.1/client/core.min.js
    @types/core-js

    jquery@3.1.1
    @types/jquery@3.3.1