id: outlook-default
name: Blank snippet
description: Create a new snippet from a blank template.
author: OfficeDev
host: OUTLOOK
api_set: null
script:
    content: |
        $("#run").click(run);

        function run() {
            OfficeHelpers.UI.notify(`Hello ${Office.context.mailbox.userProfile.displayName}`);
        }
    language: typescript
template:
    content: |
        <button id="run" class="ms-Button">
            <span class="ms-Button-label">Run</span>
        </button>
    language: html
style:
    content: |
        /* Your style goes here */
    language: css
libraries: |
    https://appsforoffice.microsoft.com/lib/1/hosted/office.js
    @types/office-js

    office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
    office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css

    core-js@2.4.1/client/core.min.js
    @types/core-js

    @microsoft/office-js-helpers@0.7.4/dist/office.helpers.min.js
    @microsoft/office-js-helpers@0.7.4/dist/office.helpers.d.ts

    jquery@3.1.1
    @types/jquery@3.3.1