id: onenote-default
name: Blank snippet
description: Create a new snippet from a blank template.
author: OfficeDev
host: ONENOTE
api_set:
    OneNoteApi: 1.1
script:
    content: |
        $("#run").click(() => tryCatch(run));

        async function run() {
            await OneNote.run(async (context) => {

                OfficeHelpers.UI.notify("Your code goes here");

                await context.sync();
            });
        }

        /** Default helper for invoking an action and handling errors. */
        async function tryCatch(callback) {
            try {
                await callback();
            }
            catch (error) {
                OfficeHelpers.UI.notify(error);
                OfficeHelpers.Utilities.log(error);
            }
        }
    language: typescript
template:
    content: |
        <button id="run" class="ms-Button">
            <span class="ms-Button-label">Run</span>
        </button>
    language: html
style:
    content: "/* Your style goes here */\r\n"
    language: css
libraries: |
    # Office.js
    https://appsforoffice.microsoft.com/lib/1/hosted/office.js

    # CSS Libraries
    office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
    office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css

    # NPM libraries
    core-js@2.4.1/client/core.min.js
    @microsoft/office-js-helpers@0.7.4/dist/office.helpers.min.js
    jquery@3.1.1

    # IntelliSense: @types/library or node_modules paths or URL to d.ts files
    @types/office-js
    @types/core-js
    @microsoft/office-js-helpers@0.7.4/dist/office.helpers.d.ts
    @types/jquery