id: ''
gist: ''
source: POWERPOINT
author: Microsoft
name: 'Blank snippet'
description: Create a new snippet from a blank template.
script:
  content: |-
    $("#run").click(run);

    function run() {
        Office.context.document.getSelectedDataAsync(Office.CoercionType.Text,
            function (asyncResult) {
                if (asyncResult.status === Office.AsyncResultStatus.Failed) {
                    console.log(asyncResult.error.message);
                } else {
                    console.log('Selected data is ' + asyncResult.value);
                }
            }
        );
    }
  language: typescript
style:
  content: /* Your style goes here */
  language: css
template:
  content: |-
    <button id="run" class="ms-Button">
        <span class="ms-Button-label">Run</span>
    </button>
  language: html
libraries: |-
  // Office.js
  https://appsforoffice.microsoft.com/lib/1/hosted/Office.js

  // NPM libraries
  jquery
  office-ui-fabric-js/dist/js/fabric.min.js
  office-ui-fabric-js/dist/css/fabric.min.css
  office-ui-fabric-js/dist/css/fabric.components.min.css
  @microsoft/office-js-helpers/dist/office.helpers.min.js
  core-js/client/core.min.js

  // IntelliSense: Use dt~library_name for DefinitelyTyped or URLs to d.ts files
  dt~office-js
  dt~jquery
  dt~core-js
  @microsoft/office-js-helpers/dist/office.helpers.d.ts
