id: excel-range-copy-multiply-values
name: Copy and multiply values
description: Copy and multiply values in a range
author: OfficeDev
host: EXCEL
api_set:
    ExcelApi: 1.1
script:
    content: |+
        $("#setup").click(setup);

        $("#copy-values").click(copyValues);
        $("#multiply-values-for-loop").click(multiplyValuesForLoop);
        $("#multiply-values-map").click(multiplyValuesMap);

        async function copyValues() {
            try {
                await Excel.run(async (context) => {
                    const sheet = context.workbook.worksheets.getItem("Sample");

                    const fromRange = sheet.getRange("B2:E5");
                    fromRange.load("values");

                    await context.sync();
                    
                    const toRange = sheet.getRange("B10:E13");
                    toRange.values = fromRange.values;

                    await context.sync();
                });
            }
            catch (error) {
                OfficeHelpers.UI.notify(error);
                OfficeHelpers.Utilities.log(error);
            }
        }

        async function multiplyValuesForLoop() {
            try {
                await Excel.run(async (context) => {
                    const sheet = context.workbook.worksheets.getItem("Sample");

                    const range = sheet.getRange("C3:C5");
                    range.load("values");

                    await context.sync();

                    var newValues = range.values;
                    for (var i = 0; i < newValues.length; i++){
                        for (var j = 0; j < newValues[i].length; j++){
                            newValues[i][j] = newValues[i][j] * 10;
                        }
                    }
                    range.values = newValues;

                    range.format.autofitColumns();
                    
                    await context.sync();
                });
            }
            catch (error) {
                OfficeHelpers.UI.notify(error);
                OfficeHelpers.Utilities.log(error);
            }
        }

        async function multiplyValuesMap() {
            try {
                await Excel.run(async (context) => {
                    const sheet = context.workbook.worksheets.getItem("Sample");

                    const range = sheet.getRange("C3:C5");
                    range.load("values");

                    await context.sync();

                    range.values = range.values.map(
                        (rowValues) => rowValues.map((cellValue) => cellValue * 10)
                    );

                    range.format.autofitColumns();
                    
                    await context.sync();
                });
            }
            catch (error) {
                OfficeHelpers.UI.notify(error);
                OfficeHelpers.Utilities.log(error);
            }
        }

        async function setup() {
            try {
                await Excel.run(async (context) => {
                    const sheet = await OfficeHelpers.ExcelUtilities
                        .forceCreateSheet(context.workbook, "Sample");
                    
                    const data = [
                        ["Product", "Qty", "Unit Price", "Total Price"],
                        ["Almonds", 2, 7.50, "=C3 * D3"],
                        ["Coffee", 1, 34.50, "=C4 * D4"],
                        ["Chocolate", 5, 9.56, "=C5 * D5"]
                    ];

                    const range = sheet.getRange("B2:E5");
                    range.values = data;
                    range.format.autofitColumns();

                    const header = range.getRow(0);
                    header.format.fill.color = "#4472C4";
                    header.format.font.color = "white";

                    sheet.activate();
                    
                    await context.sync();
                });
            }
            catch (error) {
                OfficeHelpers.UI.notify(error);
                OfficeHelpers.Utilities.log(error);
            }
        }

    language: typescript
template:
    content: |
        <section class="ms-font-m">
            <p>This sample shows how to copy, move and multiply the values in a range using the Excel API.</p>
        </section>

        <section class="setup ms-font-m">
            <h3>Set up</h3>
            <button id="setup" class="ms-Button">
                <span class="ms-Button-label">Add sample data</span>
            </button>
        </section>

        <section class="samples ms-font-m">
            <h3>Try it out</h3>
            <button id="copy-values" class="ms-Button">
                <span class="ms-Button-label">Copy values</span>
            </button>   
            <button id="multiply-values-for-loop" class="ms-Button">
                <span class="ms-Button-label">Multiply values using for loop</span>
            </button>
            <button id="multiply-values-map" class="ms-Button">
                <span class="ms-Button-label">Multiply values using map()</span>
            </button>    
        </section>
    language: html
style:
    content: |
        section.samples {
            margin-top: 20px;
        }

        section.samples .ms-Button, section.setup .ms-Button {
            display: block;
            margin-bottom: 5px;
            margin-left: 20px;
            min-width: 80px;
        }
    language: css
libraries: |
    # Office.js
    https://appsforoffice.microsoft.com/lib/1/hosted/office.js

    # CSS Libraries
    office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
    office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css

    # NPM libraries
    core-js@2.4.1/client/core.min.js
    @microsoft/office-js-helpers@0.7.4/dist/office.helpers.min.js
    jquery@3.1.1

    # IntelliSense: @types/library or node_modules paths or URL to d.ts files
    @types/office-js
    @types/core-js
    @microsoft/office-js-helpers@0.7.4/dist/office.helpers.d.ts
    @types/jquery