id: word-word-default
name: Blank snippet
description: Create a new snippet from a blank template.
author: OfficeDev
host: WORD
api_set:
    WordApi: 1.1
script:
    content: |
        $("#run").click(() => tryCatch(run));

        async function run() {
            await Word.run(async (context) => {

                OfficeHelpers.UI.notify("Your code goes here");

                await context.sync();
            });
        }

        /** Default helper for invoking an action and handling errors. */
        async function tryCatch(callback) {
            try {
                await callback();
            }
            catch (error) {
                OfficeHelpers.UI.notify(error);
                OfficeHelpers.Utilities.log(error);
            }
        }
    language: typescript
template:
    content: |
        <button id="run" class="ms-Button">
            <span class="ms-Button-label">Run</span>
        </button>
    language: html
style:
    content: |
        /* Your style goes here */
    language: css
libraries: |
    https://appsforoffice.microsoft.com/lib/1/hosted/office.js
    @types/office-js

    office-ui-fabric-js@1.4.0/dist/css/fabric.min.css
    office-ui-fabric-js@1.4.0/dist/css/fabric.components.min.css

    core-js@2.4.1/client/core.min.js
    @types/core-js

    @microsoft/office-js-helpers@0.7.4/dist/office.helpers.min.js
    @microsoft/office-js-helpers@0.7.4/dist/office.helpers.d.ts

    jquery@3.1.1
    @types/jquery