- id: project-basics-basic-common-api-call
  name: Basic API call (Office 2013)
  fileName: basic-common-api-call.yaml
  description: >-
    Executes a basic Project API call using the "common API" syntax (compatible
    with Office 2013).
  rawUrl: >-
    https://raw.githubusercontent.com/<ACCOUNT>/<REPO>/<BRANCH>/samples/project/basics/basic-common-api-call.yaml
  group: Basics
  api_set:
    Selection: 1.1
