id: outlook-mime-headers-manage-custom-internet-headers-message-compose
name: Work with custom internet headers
description: 'Sets, gets, and removes custom internet headers on a message in Compose mode.'
host: OUTLOOK
api_set:
    Mailbox: '1.8'
script:
    content: |
        $("#set-custom-headers").on("click", setCustomHeaders);
        $("#get-selected-custom-headers").on("click", getSelectedCustomHeaders);
        $("#remove-selected-custom-headers").on("click", removeSelectedCustomHeaders);

        // Set custom internet headers.
        function setCustomHeaders() {
          Office.context.mailbox.item.internetHeaders.setAsync(
            { "preferred-fruit": "orange", "preferred-vegetable": "broccoli", "best-vegetable": "spinach" },
            function (asyncResult) {
              if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
                console.log("Successfully set headers");
              } else {
                console.log("Error setting headers: " + JSON.stringify(asyncResult.error));
              }
            }

          );
        }

        // Get custom internet headers.
        function getSelectedCustomHeaders() {
          Office.context.mailbox.item.internetHeaders.getAsync(
            ["preferred-fruit", "preferred-vegetable", "best-vegetable", "nonexistent-header"],
            function (asyncResult) {
              if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
                console.log("Selected headers: " + JSON.stringify(asyncResult.value));
              } else {
                console.log("Error getting selected headers: " + JSON.stringify(asyncResult.error));
              }
            }
          );
        }

        // Remove custom internet headers.
        function removeSelectedCustomHeaders() {
          Office.context.mailbox.item.internetHeaders.removeAsync(
            ["best-vegetable", "nonexistent-header"],
            function (asyncResult) {
              if (asyncResult.status === Office.AsyncResultStatus.Succeeded) {
                console.log("Successfully removed selected headers");
              } else {
                console.log("Error removing selected headers: " + JSON.stringify(asyncResult.error));
              }
            }
          );
        }

        /* Sample output:
        Successfully set headers
        Selected headers: {"best-vegetable":"spinach","preferred-fruit":"orange","preferred-vegetable":"broccoli"}
        Successfully removed selected headers
        Selected headers: {"preferred-fruit":"orange","preferred-vegetable":"broccoli"}
        */
    language: typescript
template:
    content: |-
        <section class="ms-Fabric ms-font-m">
            <p>This sample shows how to set, get, and remove custom internet headers on a message in Compose mode.</p>
            <p><b>Required mode</b>: Message Compose</p>
        </section>
        <section class="ms-Fabric samples ms-font-m">
            <h3>Try it out</h3>
            <button id="set-custom-headers" class="ms-Button">
              <span class="ms-Button-label">Set custom headers</span>
          </button>
            <button id="get-selected-custom-headers" class="ms-Button">
              <span class="ms-Button-label">Get selected custom headers</span>
          </button>
            <button id="remove-selected-custom-headers" class="ms-Button">
              <span class="ms-Button-label">Remove selected custom headers</span>
          </button>
        </section>
    language: html
style:
    content: |-
        section.samples {
            margin-top: 20px;
        }

        section.samples .ms-Button, section.setup .ms-Button {
            display: block;
            margin-bottom: 5px;
            margin-left: 20px;
            min-width: 80px;
        }
    language: css
libraries: |
    https://appsforoffice.microsoft.com/lib/1.1/hosted/office.js
    @types/office-js

    office-ui-fabric-core@11.1.0/dist/css/fabric.min.css
    office-ui-fabric-js@1.5.0/dist/css/fabric.components.min.css

    core-js@2.4.1/client/core.min.js
    @types/core-js

    jquery@3.1.1
    @types/jquery@3.3.1