id: cj0a0l6at0000386wy16r1wxl
gist: ''
host: EXCEL
api_set: {}
platform: null
created_at: 1489524765275
modified_at: 1489524836328
origin: 'https://bornholm-edge.azurewebsites.net'
author: Microsoft
name: Blank snippet
description: Create a new snippet from a blank template.
script:
  content: |
    $("#run").click(run);

    async function run() {
        try {
            await Excel.run(async (context) => {
                console.log("Your code goes here");
                await context.sync();
            });
        }
        catch (error) {
            OfficeHelpers.Utilities.log(error);
        }
    }
  language: typescript
style:
  content: "/* Your style goes here */\r\n"
  language: css
template:
  content: |
    <button id="run" class="ms-Button">
        <span class="ms-Button-label">Run</span>
    </button>
  language: html
libraries: |
  # Office.js
  https://appsforoffice.microsoft.com/lib/1/beta/hosted/office.js

  # CSS Libraries
  office-ui-fabric-js@1.4.0/dist/css/fabric.min.css

  # NPM libraries
  core-js@2.4.1/client/core.min.js
  @microsoft/office-js-helpers@0.5.0/dist/office.helpers.min.js
  jquery@3.1.1

  # IntelliSense: @types/library or node_modules paths or URL to d.ts files
  @types/office-js
  @types/core-js
  @microsoft/office-js-helpers/dist/office.helpers.d.ts
  @types/jquery
