id: project-default
name: Blank snippet
description: Create a new snippet from a blank template.
author: OfficeDev
host: PROJECT
api_set: {}
script:
    content: >-
        document.getElementById("run").addEventListener("click", run);


        function run() {
            Office.context.document.getSelectedDataAsync(Office.CoercionType.Text, (asyncResult) => {
                if (asyncResult.status === Office.AsyncResultStatus.Failed) {
                    console.error(asyncResult.error.message);
                } else {
                    console.log(`The selected data is "${asyncResult.value}".`);
                }
            });
        }
    language: typescript
template:
    content: |-
        <button id="run" class="ms-Button">
            <span class="ms-Button-label">Run</span>
        </button>
    language: html
style:
    content: |-
        section.samples {
            margin-top: 20px;
        }

        section.samples .ms-Button, section.setup .ms-Button {
            display: block;
            margin-bottom: 5px;
            margin-left: 20px;
            min-width: 80px;
        }
    language: css
libraries: |-
    https://appsforoffice.microsoft.com/lib/1/hosted/office.js
    https://appsforoffice.microsoft.com/lib/1/hosted/office.d.ts

    https://unpkg.com/office-ui-fabric-core@11.1.0/dist/css/fabric.min.css
    https://unpkg.com/office-ui-fabric-js@1.5.0/dist/css/fabric.components.min.css
